implement task 1
jjanickamatraszek/SeleniumPractice pull request #1
Opened 2023-05-16 13:59 UTC by jjanickamatraszek

add basic pages for HomePage, MainMenu, NewInSubMenu
implement one sample test scenario (display submenu of 'New In' menu category)

2023-05-18 13:40 UTC, Trukhanovich approved these changes
lgtm

2023-05-19 10:01 UTC, kzukowski-solvd requested changes
Some changes ;P

2023-05-19 10:01 UTC, kzukowski-solvd commented on src/main/java/com/solvd/components/MainMenu.java
> +    @FindBy(xpath = ".//ul[@data-testid='category-list']//span[contains(text(),'new in')]/parent::li")
According to the 5th point in the task specification web elements should have css selectors.

2023-05-19 10:01 UTC, kzukowski-solvd commented on src/main/java/com/solvd/components/NewInSubMenu.java
> +    @FindBy(xpath = ".//span[contains(text(),'new in')]/parent::li//ul[contains(@class,'inner-list')]")
xpath -> css

2023-05-19 10:01 UTC, kzukowski-solvd commented on src/main/java/com/solvd/components/NewInSubMenu.java
> +    @FindBy(xpath = ".//span[contains(text(),'new in')]/parent::li//ul/div[contains(@class,'photo-section')]")
xpath -> css

2023-05-19 12:29 UTC, jjanickamatraszek commented on src/main/java/com/solvd/components/MainMenu.java
> +    @FindBy(xpath = ".//ul[@data-testid='category-list']//span[contains(text(),'new in')]/parent::li")
I use text() method from xpath to be sure that 'new in' element is clicked and text() is not supported by css

2023-05-19 12:29 UTC, jjanickamatraszek commented on src/main/java/com/solvd/components/NewInSubMenu.java
> +    @FindBy(xpath = ".//span[contains(text(),'new in')]/parent::li//ul[contains(@class,'inner-list')]")
the same case as above -> i use text() from xpath

2023-05-19 12:30 UTC, jjanickamatraszek commented on src/main/java/com/solvd/components/NewInSubMenu.java
> +    @FindBy(xpath = ".//span[contains(text(),'new in')]/parent::li//ul/div[contains(@class,'photo-section')]")
the same case as above -> i use text() from xpath

2023-05-19 12:36 UTC, merged